Battleship game review
pelzolga123/Battleship pull request #1
Opened 2019-12-20 21:37 UTC by pelzolga123

### Things we implemented in this project:
* Created Board factory
* Created Ships factory
* Implemented drag and drop
* Implemented random ships placement
* Created game logic
* Added tests for Ships and Board

2019-12-21 07:14 UTC, Oghenebrume50 requested changes
STATUS: CHANGES REQUIRED 

Hi Team, overall this is a good start :clap: :clap:  but in order to achieve the best version of this,  I have made a couple of suggestions but they are not exhaustive, so please see read the comments below. 

- It will be a lot easier if you guys abstract the DOM manipulation from the game logic, there should be a file that handles the DOM manipulation and anything that involves display.
- Let us stick to using factory functions for what they are, Ship, board should be reusable factories that has all their fucntionalities in them, creating methods outside to perform this tasks beats the idea. 
For example, we don't need a isSunk function outside the Ship factory, the Ship factory should have one in it and that's it.
- Please try to fix all suggestions by stickler, they are super important, especially the issue with circular dependency 
- disabling eslint rule in each file is not good practice create a better rule in the eslint file

And I see this when I try to run the project, it is blank :slightly_frowning_face: : I am not sure if I did something wrong, but it doesn't look like it 
![11](https://user-images.githubusercontent.com/37092867/71304594-57ffc500-23c9-11ea-8555-80226bebe849.png)

Please let us look into that :slightly_smiling_face: 

Raphael Noriode :sunglasses:

2019-12-21 07:14 UTC, Oghenebrume50 commented on src/board.js
> +/* eslint-disable import/no-cycle */
cycle dependency is not good in programming, please remove this line from here and everywhere else it occurs and fix the dependency issue [see this](https://spin.atomicobject.com/2018/06/25/circular-dependencies-javascript/)

2019-12-21 07:14 UTC, Oghenebrume50 commented on src/ships.js
> +  hits: 0,
so the hit function in the Ship factory should be a method on it's own that does this job ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/battleship/hit_requirement.png)

2019-12-21 07:14 UTC, Oghenebrume50 commented on src/ships.js
> +const Ships = (player, fc) => ({
This factory should also have an isSunk function to check when this ship is sunk ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/battleship/sunk_requirement.png)

2019-12-21 07:14 UTC, Oghenebrume50 commented on src/board.js
> +const Board = field => ({
As factory functions go, please create the missedhit and allSunk in it, so it can be resuable, this is the idea of factories so you use instances ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/battleship/gameboard_requirement.png)

2019-12-21 09:31 UTC, pelzolga123 commented
Hi Rachel, why is status: approved?

2019-12-21 09:37 UTC, Oghenebrume50 commented
Hi, that was a mistake I have made the correction

2020-01-13 16:46 UTC, pelzolga123 commented
> ### Things we implemented in this project:
> * Created Board factory
> * Created Ships factory
> * Implemented random ships placement
> * Created game logic
> * Added tests for Ships and Board

2020-01-14 05:07 UTC, bellom requested changes
## Hi Team :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

**Just one confusing part 🤔  
Is it that the game will play automatically ?
check out the video review link below;**

https://www.loom.com/share/27aa379c647348a6be6a27dc356bd17f

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,
**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-14 05:07 UTC, bellom commented on src/board.js
> +    // board border is too close
**Comments: It’s better to delete all commented code in your files**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-01-14 09:56 UTC, pelzolga123 commented on src/board.js
> +    // board border is too close
We removed all comments and increased time for user to shoot, just as requested.

2020-01-14 09:59 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Goodluck in the next project :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-14 10:01 UTC, merged